import matplotlib.pyplot as plt
import joblib
import pandas as pd
import numpy as np

def generate_save_feature_plot(df: pd.DataFrame, model: object, model_type: str = "elastic_net"):
    """
    Generate, save, and display a horizontal bar plot of feature importances or coefficient magnitudes.

    This function extracts relative feature contributions based on the specified model type:
    - For 'elastic_net', it assumes a scikit-learn Pipeline, extracts non-zero coefficients 
      using feature names generated by the preprocessor step, and plots their absolute values.
    - For tree-based models (e.g., LightGBM, XGBoost), it pairs the raw columns of `df` 
      directly with the model's native `feature_importances_` array.

    The resulting plot is sorted in descending order, saved locally as a high-resolution 
    PNG file, and rendered to the active plotting state.

    Parameters
    ----------
    df : pandas.DataFrame
        The DataFrame used to map raw column names to `feature_importances_` when 
        `model_type` is not "elastic_net".
    model : object
        A trained estimator or pipeline instance. 
        - If `model_type` is "elastic_net", it must be a scikit-learn Pipeline object with 
          'preprocessor' and 'model' steps.
        - For other types, it must expose a `feature_importances_` attribute.
    model_type : str, default="elastic_net"
        The type of model being visualized. Determines the metric extracted ("elastic_net" 
        vs. tree frameworks) and controls the plot titles and file naming conventions.

    Returns
    -------
    pandas.DataFrame
        A structured DataFrame containing 'feature' names alongside their respective metrics
        ('coefficient_absolute_value' or 'importance'), sorted in descending order.
    """
    if model_type == "elastic_net":
        y_axis_value, title_text = "coefficient_absolute_value", "Magnitude of Coefficients"
        feature_df = pd.DataFrame({
            "feature": model.named_steps['preprocessor'].get_feature_names_out(),
            "coefficients": model.named_steps['model'].coef_
        })

        feature_df = feature_df[feature_df["coefficients"] != 0]
        feature_df["coefficient_absolute_value"] = feature_df["coefficients"].abs()

    else: 
        y_axis_value, title_text = "importance", "Feature Importance"
        feature_df = pd.DataFrame({
            "feature": df.columns,
            "importance": model.feature_importances_
        })

    sorted_df = feature_df.sort_values(y_axis_value, ascending=False)
    sorted_df.plot(
        x="feature", y=y_axis_value, kind="barh", figsize=(15,9), color="#2a9d8f"
    )

    plt.title(f"{title_text} of {model_type} model")
    plt.savefig(f"./outputs/plots/{model_type}_{y_axis_value}.png", bbox_inches="tight", dpi=300)

    return sorted_df 

def save_model_object(model, best_params, eval_metric, feature_vals, model_name: str = "elastic_net"):
    """
    Serialize and save a trained model, hyperparameters, metrics, and feature values to disk.

    This function bundles the provided model object along with its best hyperparameters,
    evaluation metrics (RMSE), and feature-specific values (coefficients or importances) 
    into a single dictionary and persists it using `joblib`. The output file is saved to 
    `./outputs/models/{model_name}_artifacts.pkl`.

    Parameters
    ----------
    model : object
        The trained model or pipeline object to be persisted. Must be serializable 
        by `joblib` (e.g., scikit-learn estimators or pipelines).
    best_params : dict
        Mapping of the best hyperparameters found during tuning (e.g., from 
        GridSearchCV or RandomizedSearchCV).
    eval_metric : float or scalar
        The evaluation metric value (e.g., RMSE) to be stored alongside the model.
    feature_vals : array-like or list
        The feature values to persist. For "elastic_net" models, this typically 
        represents non-zero coefficients. For other models, it represents feature 
        importances. The length of this list may differ from the original feature 
        set length (e.g., if only non-zero features are included).
    model_name : str, default="elastic_net"
        Base name used to construct the output filename. Determines the column key 
        name in the saved dictionary:
        - "elastic_net" -> key: "feature_coefficients"
        - Other -> key: "feature_importances"
    """
    feature_col_name = "feature_coefficients" if model_name == "elastic_net" else "feature_importances"
    joblib.dump({
        "model": model,
        "best_params": best_params,
        "rmse": eval_metric,
        feature_col_name: feature_vals
    }, f"./outputs/models/{model_name}_artifacts.pkl")

def save_model_predictions(pred_values, y_test, x_test: pd.DataFrame, model_name: str = "elastic_net"):
    """
    Create a DataFrame of predictions and save it to a CSV file.

    This function constructs a results table containing the sample identifier 
    (derived from the index of `x_test`), the actual target values, predicted 
    values, and error metrics (absolute and signed error). The resulting DataFrame 
    is saved to `./outputs/predictions/{model_name}_predictions.csv`.

    Parameters
    ----------
    pred_values : array-like
        The predicted values generated by the model. Must be aligned with the 
        rows of `x_test` and `y_test`.
    y_test : array-like
        The ground truth (actual) target values. Must be aligned with `x_test` 
        and `pred_values`.
    x_test : pandas.DataFrame
        The test feature DataFrame. Its index is used to generate the unique 
        sample identifier (`id`) in the output file.
    model_name : str, default="elastic_net"
        The base name used to construct the output filename. The file will be 
        saved as `{model_name}_predictions.csv`.

    Returns
    -------
    pandas.DataFrame
        A DataFrame containing the columns:
        - `id`: Sample identifier from `x_test.index`.
        - `actual`: Ground truth values.
        - `prediction`: Model predictions.
        - `error`: Signed difference (`actual - prediction`).
        - `abs_error`: Absolute difference (`|actual - prediction|`).
    """

    prediction_df = pd.DataFrame({
        "id": x_test.index,
        "actual": y_test,
        "prediction": pred_values,
        "error": y_test - pred_values,
        "abs_error": np.abs(y_test - pred_values)
    })

    prediction_df.to_csv(f"./outputs/predictions/{model_name}_predictions.csv", index=False)

    return prediction_df
